### PR TITLE
v2.9 related version bumps

### LINKED ISSUE #103: Branch rancher/hosted-providers-e2e, Bump Go and rancher/shepherd versions
- [ ] Branch the repo into 2 parts: release/v2.8 and main or release/v2.9
- [ ] release/v2.8 should use Go 1.21, and main Go 1.22 (this pattern is followed by rancher/rancher and rancher/shepherd)
- [ ] release/v2.8 will use rancher/shepherd release/v2.8 branch and same for the main.

### PR DESCRIPTION
**Pull request by cpinjani**
### What does this PR do?
Bumps dependencies for v2.9 which are followed by rancher/rancher and rancher/shepherd

### Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #103 

### Checklist:
- [x] Squashed commits into logical changes
- [x] Documentation
- [x] GitHub Actions:
AKS - [P0](https://github.com/rancher/hosted-providers-e2e/actions/runs/9465563453), [SupportMatrix](https://github.com/rancher/hosted-providers-e2e/actions/runs/9466842644)
EKS - [P0](https://github.com/rancher/hosted-providers-e2e/actions/runs/9477951949), [SupportMatrix](https://github.com/rancher/hosted-providers-e2e/actions/runs/9477481818)
GKE - [P0](https://github.com/rancher/hosted-providers-e2e/actions/runs/9477464104), [SupportMatrix](https://github.com/rancher/hosted-providers-e2e/actions/runs/9478298953)

### Special notes for your reviewer:
- Will create branch release/v2.8 out of current main, before merge.
- Separate issue for failing jobs: https://github.com/rancher/hosted-providers-e2e/issues/117

### CODE REVIEW

**Comment by valaparthvi** [comment]
The PR looks fine to me, but can we branch out to release-v2.8 before merging this?

**Comment by valaparthvi** [comment]
> The PR looks fine to me, but can we branch out to release-v2.8 before merging this?

I have created a new branch called `release-v2.8`.

**Review by valaparthvi — APPROVED** [review]

**Comment by cpinjani** [comment]
> > The PR looks fine to me, but can we branch out to release-v2.8 before merging this?
> 
> I have created a new branch called `release-v2.8`.

nit: Branch name - release/v2.8

**Comment by valaparthvi** [comment]
> > > The PR looks fine to me, but can we branch out to release-v2.8 before merging this?
> > 
> > 
> > I have created a new branch called `release-v2.8`.
> 
> nit: Branch name - release/v2.8

Done. Also, once this is done we might need to delete the scheduled jobs from [release/v2.8](https://github.com/rancher/hosted-providers-e2e/tree/release/v2.8).

**Pull request merged**
